// services/quizService.js
// Stub in-memory quiz service. Real implementation should use Supabase
// (quizzes + quiz_questions tables) + AI via aiService + RAG contextBuilder.
// selectedTopics semantics per .trae/specs:
//   empty array / undefined → blind "all content" Strategy B (diverse coverage)
//   non-empty string[]      → Strategy A anchored on those topic labels

const quizzesBySpace = new Map(); // spaceId -> Quiz[]

function coerceSelectedTopics(v) {
  if (Array.isArray(v)) return v.filter((x) => typeof x === "string");
  return [];
}

function normalize(quiz) {
  if (!quiz) return quiz;
  return {
    id: quiz.id,
    space_id: quiz.space_id,
    title: quiz.title,
    question_count: quiz.question_count,
    difficulty: quiz.difficulty,
    selected_topics: Array.isArray(quiz.selected_topics)
      ? quiz.selected_topics
      : [],
    best_score: quiz.best_score ?? null,
    attempts_count: quiz.attempts_count ?? 0,
    leaderboard: Array.isArray(quiz.leaderboard) ? quiz.leaderboard : [],
    created_at: quiz.created_at,
  };
}

function quizService() {
  return {
    listForSpace(spaceId) {
      const rows = quizzesBySpace.get(spaceId) || [];
      return rows.map(normalize);
    },

    generate(params) {
      const spaceId = params.spaceId;
      const selectedTopics = coerceSelectedTopics(params.selectedTopics);
      const questionCount = Math.max(
        1,
        Math.min(100, Number(params.questionCount) || 20),
      );
      const difficulty = String(params.difficulty || "Mixed");

      const title =
        selectedTopics.length > 0
          ? `${selectedTopics[0]} Focus Quiz (${difficulty})`
          : `Custom ${difficulty} Quiz (${questionCount} Qs)`;

      const quiz = {
        id: `q-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`,
        space_id: spaceId,
        title,
        question_count: questionCount,
        difficulty,
        selected_topics: selectedTopics,
        best_score: null,
        attempts_count: 0,
        leaderboard: [],
        created_at: new Date().toISOString(),
        // TODO (real impl): questions[] generated by AI, insert quiz_questions
      };

      const arr = quizzesBySpace.get(spaceId) || [];
      arr.unshift(quiz);
      quizzesBySpace.set(spaceId, arr);

      return normalize(quiz);
    },

    delete(spaceId, quizId) {
      const arr = quizzesBySpace.get(spaceId) || [];
      const next = arr.filter((q) => q.id !== quizId);
      quizzesBySpace.set(spaceId, next);
      return next.length < arr.length;
    },
  };
}

module.exports = { quizService };
